open-key="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"
open-weather="3a7f36952c9b751645c34067d0382206"
pinecone_api_key="pcsk_6reuE9_QNTBXM9quQqBZcBtXSMydyBuWMhRfZhpHmdbPH2huGt8H4bv3ATG2SW6zxC2PA3"