open-key="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"
open-weather="3a7f36952c9b751645c34067d0382206"