open-key="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"
open-weather="3a7f36952c9b751645c34067d0382206"